[general]

import = [
  "~/.config/alacritty/themes/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]

padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.6
blur = true
option_as_alt = "OnlyLeft"

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13
offset = { x = 1 }
